baseURL = 'https://goedoverleven.nl/'
languageCode = 'nl'
title = 'Goed Overleven'
theme = 'ramp'
disableKinds = ["taxonomy", "term", "rss"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = "monthly"
  priority = 0.8
  filename = "sitemap.xml"




[params]
    tagline = 'Uw Gids voor Paraatheid'
    description = 'Word écht voorbereid op elke crisis met Goed Overleven. Ontdek complete gidsen, praktische tips & essentiële kennis voor noodsituaties en zelfredzaamheid. Bescherm uw gezin vandaag nog!'
    logo = '/images/goedoverleven.webp'
    favicon = '/goedoverleven.ico'